/// @description Initialize
image_speed = 0;
owner = noone;
name = "";
choices = ds_list_create();
selection = noone;
index = undefined;
previous_index = undefined;
enabled = false;
remember = true;
wrap = false;
event_select = "start";
event_descend = "up";
event_ascend = "down";