/// @description Initialize
image_speed = 0;
soundid = -1;
priority = 0;
loops = false;
playing = false;
finished = false;
index = -1;
position = 0;
next = noone;
previous = noone;
intro_length = 0;
loop_length = 0;