/// @description Initialize
event_inherited();
state = "entering";
duration = 45;

fadeDuration = 22;
fadeColor = c_black;
fadeAlpha = 0.75;

font = global.CrackersFont;
fontColor = c_white;

warningText = "THIS IS A NON-PROFIT FAN-BASED PROJECT FOR FREEWARE DISTRIBUTION ONLY. ALL COPYRIGHTS AND REGISTERED TRADEMARKS OF 'SONIC THE HEDGEHOG' AND ALL ASSOCIATED CHARACTERS, ART, NAMES, TERMS AND MUSIC BELONG TO SEGA® AND ARE NOT SUBJECT TO THE LICENSE ASSOCIATED WITH THIS PROJECT. THE CONTRIBUTORS TO THIS SOFTWARE ARE IN NO WAY AFFILIATED WITH SEGA® OR SONIC TEAM®, NOR IS ANY INTENT MADE TO GAIN FINANCIALLY FROM OR INFRINGE UPON SAID COPYRIGHTS OR REGISTERED TRADEMARKS."
warningX = CAMERA_WIDTH * 0.5;
warningY = CAMERA_HEIGHT * 0.5;

startText = "";
startX = CAMERA_WIDTH * 0.5;
startY = CAMERA_HEIGHT * 0.75;