// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // FMODAudioSystem
global.__objectDepths[1] = 0; // FMODGameMusic
global.__objectDepths[2] = 0; // FMODTimedGameMusic
global.__objectDepths[3] = 0; // GameAudioConfiguration
global.__objectDepths[4] = 0; // GMSAudioSystem
global.__objectDepths[5] = 0; // GMSGameMusic
global.__objectDepths[6] = 0; // GMSJingle
global.__objectDepths[7] = 0; // GMSTimedGameMusic
global.__objectDepths[8] = 0; // GameAudioSystem
global.__objectDepths[9] = 0; // GameMusic
global.__objectDepths[10] = 0; // FPSProfile
global.__objectDepths[11] = 0; // GameClock
global.__objectDepths[12] = 0; // GameConsole
global.__objectDepths[13] = 0; // GameInputConfiguration
global.__objectDepths[14] = 0; // GameSaveDirectory
global.__objectDepths[15] = 0; // GameSaveFile
global.__objectDepths[16] = 0; // CRTFilter
global.__objectDepths[17] = 0; // SpriteParticles
global.__objectDepths[18] = 1024; // ParallaxLayer
global.__objectDepths[19] = 1024; // ParallaxSpriteLayer
global.__objectDepths[20] = -128; // DrownPopup
global.__objectDepths[21] = 0; // ScorePopup
global.__objectDepths[22] = 0; // AdaptedGameWindow
global.__objectDepths[23] = 0; // GameWindow
global.__objectDepths[24] = 0; // Gamepad
global.__objectDepths[25] = 0; // Keyboard
global.__objectDepths[26] = 0; // InputSource
global.__objectDepths[27] = 0; // PlayerCamera
global.__objectDepths[28] = 0; // InvincibilityEffect
global.__objectDepths[29] = -1; // InvincibilitySpark
global.__objectDepths[30] = 0; // PlayerDashSmoke
global.__objectDepths[31] = -2; // SuperFormShader
global.__objectDepths[32] = 0; // TailsTails
global.__objectDepths[33] = 0; // PlayerEffect
global.__objectDepths[34] = 0; // PlayerShield
global.__objectDepths[35] = 0; // AquaShield
global.__objectDepths[36] = 0; // FlameShield
global.__objectDepths[37] = 0; // StandardShield
global.__objectDepths[38] = 0; // ThunderShield
global.__objectDepths[39] = 0; // PlayableCharacter
global.__objectDepths[40] = 0; // Knuckles
global.__objectDepths[41] = 0; // Sonic
global.__objectDepths[42] = 0; // Tails
global.__objectDepths[43] = 0; // ComputerPlayer
global.__objectDepths[44] = 0; // GamePlayer
global.__objectDepths[45] = 0; // RealPlayer
global.__objectDepths[46] = 0; // ContinueScreenCharacter
global.__objectDepths[47] = 0; // ContinueScreenKnuckles
global.__objectDepths[48] = 0; // ContinueScreenSonic
global.__objectDepths[49] = 0; // ContinueScreenTails
global.__objectDepths[50] = 1; // ContinueScreenTailsAssist
global.__objectDepths[51] = 0; // ContinueScreen
global.__objectDepths[52] = 0; // CreditsSequence
global.__objectDepths[53] = 0; // SonicGMSSplashScreen
global.__objectDepths[54] = 0; // SonicTheHedgehogTitle
global.__objectDepths[55] = 0; // PausedScreen
global.__objectDepths[56] = -1000; // LegalDisclaimer
global.__objectDepths[57] = 0; // GameSuspension
global.__objectDepths[58] = -10; // FadeIn
global.__objectDepths[59] = -10; // FadeOut
global.__objectDepths[60] = 0; // ScreenTransition
global.__objectDepths[61] = 0; // AnimalFriend
global.__objectDepths[62] = 0; // Flicky
global.__objectDepths[63] = 0; // Ricky
global.__objectDepths[64] = 0; // Bridge
global.__objectDepths[65] = 0; // Bumper
global.__objectDepths[66] = 0; // ScoreBumper
global.__objectDepths[67] = 0; // Camera
global.__objectDepths[68] = 0; // Capsule
global.__objectDepths[69] = 16; // Sonic2Capsule
global.__objectDepths[70] = 0; // DevControl
global.__objectDepths[71] = 0; // DevVisualization
global.__objectDepths[72] = 0; // CameraLock
global.__objectDepths[73] = 0; // DeathZone
global.__objectDepths[74] = 0; // LayerFlip
global.__objectDepths[75] = 0; // PanningCameraLock
global.__objectDepths[76] = 9999; // Region
global.__objectDepths[77] = 0; // BossEnemy
global.__objectDepths[78] = 0; // Enemy
global.__objectDepths[79] = 0; // RhinoBot
global.__objectDepths[80] = 0; // MovingSpikeTrap
global.__objectDepths[81] = 0; // SpikeTrap
global.__objectDepths[82] = 8; // BrokenMonitor
global.__objectDepths[83] = 8; // Monitor
global.__objectDepths[84] = 7; // AquaShieldIcon
global.__objectDepths[85] = 7; // EggmanIcon
global.__objectDepths[86] = 7; // ExtraLifeIcon
global.__objectDepths[87] = 7; // FlameShieldIcon
global.__objectDepths[88] = 7; // InvincibilityIcon
global.__objectDepths[89] = 0; // MonitorIcon
global.__objectDepths[90] = 7; // RingsIcon
global.__objectDepths[91] = 7; // ShieldIcon
global.__objectDepths[92] = 7; // SuperFormIcon
global.__objectDepths[93] = 7; // SuperSpeedIcon
global.__objectDepths[94] = 7; // ThunderShieldIcon
global.__objectDepths[95] = 0; // Deactivable
global.__objectDepths[96] = 0; // Solid
global.__objectDepths[97] = 0; // CompetitionSignPost
global.__objectDepths[98] = 1024; // DefaultPlayerEntrance
global.__objectDepths[99] = 0; // LampPost
global.__objectDepths[100] = 0; // PlayerEntrance
global.__objectDepths[101] = 0; // SignPost
global.__objectDepths[102] = 10; // Sonic2LampPost
global.__objectDepths[103] = 10; // Sonic2SignPost
global.__objectDepths[104] = 0; // LostRing
global.__objectDepths[105] = 0; // MagnetizedRing
global.__objectDepths[106] = 0; // Ring
global.__objectDepths[107] = 0; // WorldRing
global.__objectDepths[108] = 0; // HeavyRectangle
global.__objectDepths[109] = 0; // QuarterEllipse
global.__objectDepths[110] = 0; // QuarterPipe
global.__objectDepths[111] = 0; // Rectangle
global.__objectDepths[112] = 0; // RightTriangle
global.__objectDepths[113] = 0; // DiagonalSpring
global.__objectDepths[114] = 0; // RedDiagonalSpring
global.__objectDepths[115] = 0; // YellowDiagonalSpring
global.__objectDepths[116] = 0; // RedSpring
global.__objectDepths[117] = 0; // Spring
global.__objectDepths[118] = 0; // YellowSpring
global.__objectDepths[119] = 0; // SolidSwitch
global.__objectDepths[120] = 0; // Switch
global.__objectDepths[121] = -4; // BreakableWallDebris
global.__objectDepths[122] = 0; // BreakableWall
global.__objectDepths[123] = 0; // CrumblingFloor
global.__objectDepths[124] = 0; // CrumblingFloorPiece
global.__objectDepths[125] = 1; // QuarterEllipseConstruct
global.__objectDepths[126] = 1; // QuarterPipeConstruct
global.__objectDepths[127] = 1; // QuarterEllipseTerrain
global.__objectDepths[128] = 1; // QuarterPipeTerrain
global.__objectDepths[129] = 1; // RectangleTerrain
global.__objectDepths[130] = 1; // RightTriangleTerrain
global.__objectDepths[131] = -1; // Bubble
global.__objectDepths[132] = 0; // BubbleCluster
global.__objectDepths[133] = 99999; // Water
global.__objectDepths[134] = 1; // WaterBlend
global.__objectDepths[135] = 1; // WaterRippleShader
global.__objectDepths[136] = 0; // GameZone
global.__objectDepths[137] = 0; // PauseControl
global.__objectDepths[138] = 0; // ZoneCleanup
global.__objectDepths[139] = 0; // ZoneTimeLimit
global.__objectDepths[140] = 0; // ZoneRestart
global.__objectDepths[141] = 0; // AzureLakeBackground
global.__objectDepths[142] = 1024; // TestRoomBackground
global.__objectDepths[143] = 0; // ConveyorBelt
global.__objectDepths[144] = 4; // Corkscrew
global.__objectDepths[145] = 0; // MovableWater
global.__objectDepths[146] = 0; // PushBlock
global.__objectDepths[147] = 0; // SampleBreakableWall
global.__objectDepths[148] = 0; // SampleBridge
global.__objectDepths[149] = 0; // SampleScoreBumper
global.__objectDepths[150] = 10; // BossEggMobile
global.__objectDepths[151] = 10; // BossEggMobileEggman
global.__objectDepths[152] = 11; // GHZBossChainBall
global.__objectDepths[153] = 12; // GHZBossChainBase
global.__objectDepths[154] = 12; // GHZBossChainLink
global.__objectDepths[155] = 0; // GHZBossEggMobile
global.__objectDepths[156] = 0; // DemoZoneBoss
global.__objectDepths[157] = 0; // CrushBlock
global.__objectDepths[158] = 0; // HorizontalMovingBlock
global.__objectDepths[159] = 0; // VerticalMovingBlock
global.__objectDepths[160] = 0; // CustomTerrain1
global.__objectDepths[161] = 0; // CustomTerrain2
global.__objectDepths[162] = 0; // CustomTerrain3
global.__objectDepths[163] = 0; // FileSelectMenuChoice
global.__objectDepths[164] = 0; // FileSelectMenuFileChoice
global.__objectDepths[165] = 0; // FileSelectMenuCompleteFileChoice
global.__objectDepths[166] = 0; // FileSelectMenuDeleteChoice
global.__objectDepths[167] = 0; // FileSelectMenuExistingFileChoice
global.__objectDepths[168] = 0; // FileSelectMenuNewFileChoice
global.__objectDepths[169] = 0; // FileSelectMenuNoSaveChoice
global.__objectDepths[170] = 0; // FileSelectMenu
global.__objectDepths[171] = -1; // FileSelectMenuCursor
global.__objectDepths[172] = -2; // FileSelectMenuDeleteIcon
global.__objectDepths[173] = 0; // FileSelectMenuPage
global.__objectDepths[174] = 0; // GameMenuChoice
global.__objectDepths[175] = 0; // LabelledMenuChoice
global.__objectDepths[176] = 0; // LabelledMouseSensitiveMenuChoice
global.__objectDepths[177] = 0; // MouseSensitiveMenuChoice
global.__objectDepths[178] = 0; // GameMenu
global.__objectDepths[179] = 0; // GameMenuPage
global.__objectDepths[180] = 0; // GameOverScreen
global.__objectDepths[181] = 0; // TimeOverScreen
global.__objectDepths[182] = -2; // ScoreTally
global.__objectDepths[183] = -1; // Sonic2Display
global.__objectDepths[184] = -1000; // AnimatedGameSign
global.__objectDepths[185] = -1000; // AnimatedLabeledGameSign
global.__objectDepths[186] = 0; // GameSign
global.__objectDepths[187] = 0; // LabeledGameSign
global.__objectDepths[188] = -2; // ZoneTitle
global.__objectDepths[189] = 0; // ZoneTitleRedFold
global.__objectDepths[190] = -1000; // GameConsoleMessage


global.__objectNames[0] = "FMODAudioSystem";
global.__objectNames[1] = "FMODGameMusic";
global.__objectNames[2] = "FMODTimedGameMusic";
global.__objectNames[3] = "GameAudioConfiguration";
global.__objectNames[4] = "GMSAudioSystem";
global.__objectNames[5] = "GMSGameMusic";
global.__objectNames[6] = "GMSJingle";
global.__objectNames[7] = "GMSTimedGameMusic";
global.__objectNames[8] = "GameAudioSystem";
global.__objectNames[9] = "GameMusic";
global.__objectNames[10] = "FPSProfile";
global.__objectNames[11] = "GameClock";
global.__objectNames[12] = "GameConsole";
global.__objectNames[13] = "GameInputConfiguration";
global.__objectNames[14] = "GameSaveDirectory";
global.__objectNames[15] = "GameSaveFile";
global.__objectNames[16] = "CRTFilter";
global.__objectNames[17] = "SpriteParticles";
global.__objectNames[18] = "ParallaxLayer";
global.__objectNames[19] = "ParallaxSpriteLayer";
global.__objectNames[20] = "DrownPopup";
global.__objectNames[21] = "ScorePopup";
global.__objectNames[22] = "AdaptedGameWindow";
global.__objectNames[23] = "GameWindow";
global.__objectNames[24] = "Gamepad";
global.__objectNames[25] = "Keyboard";
global.__objectNames[26] = "InputSource";
global.__objectNames[27] = "PlayerCamera";
global.__objectNames[28] = "InvincibilityEffect";
global.__objectNames[29] = "InvincibilitySpark";
global.__objectNames[30] = "PlayerDashSmoke";
global.__objectNames[31] = "SuperFormShader";
global.__objectNames[32] = "TailsTails";
global.__objectNames[33] = "PlayerEffect";
global.__objectNames[34] = "PlayerShield";
global.__objectNames[35] = "AquaShield";
global.__objectNames[36] = "FlameShield";
global.__objectNames[37] = "StandardShield";
global.__objectNames[38] = "ThunderShield";
global.__objectNames[39] = "PlayableCharacter";
global.__objectNames[40] = "Knuckles";
global.__objectNames[41] = "Sonic";
global.__objectNames[42] = "Tails";
global.__objectNames[43] = "ComputerPlayer";
global.__objectNames[44] = "GamePlayer";
global.__objectNames[45] = "RealPlayer";
global.__objectNames[46] = "ContinueScreenCharacter";
global.__objectNames[47] = "ContinueScreenKnuckles";
global.__objectNames[48] = "ContinueScreenSonic";
global.__objectNames[49] = "ContinueScreenTails";
global.__objectNames[50] = "ContinueScreenTailsAssist";
global.__objectNames[51] = "ContinueScreen";
global.__objectNames[52] = "CreditsSequence";
global.__objectNames[53] = "SonicGMSSplashScreen";
global.__objectNames[54] = "SonicTheHedgehogTitle";
global.__objectNames[55] = "PausedScreen";
global.__objectNames[56] = "LegalDisclaimer";
global.__objectNames[57] = "GameSuspension";
global.__objectNames[58] = "FadeIn";
global.__objectNames[59] = "FadeOut";
global.__objectNames[60] = "ScreenTransition";
global.__objectNames[61] = "AnimalFriend";
global.__objectNames[62] = "Flicky";
global.__objectNames[63] = "Ricky";
global.__objectNames[64] = "Bridge";
global.__objectNames[65] = "Bumper";
global.__objectNames[66] = "ScoreBumper";
global.__objectNames[67] = "Camera";
global.__objectNames[68] = "Capsule";
global.__objectNames[69] = "Sonic2Capsule";
global.__objectNames[70] = "DevControl";
global.__objectNames[71] = "DevVisualization";
global.__objectNames[72] = "CameraLock";
global.__objectNames[73] = "DeathZone";
global.__objectNames[74] = "LayerFlip";
global.__objectNames[75] = "PanningCameraLock";
global.__objectNames[76] = "Region";
global.__objectNames[77] = "BossEnemy";
global.__objectNames[78] = "Enemy";
global.__objectNames[79] = "RhinoBot";
global.__objectNames[80] = "MovingSpikeTrap";
global.__objectNames[81] = "SpikeTrap";
global.__objectNames[82] = "BrokenMonitor";
global.__objectNames[83] = "Monitor";
global.__objectNames[84] = "AquaShieldIcon";
global.__objectNames[85] = "EggmanIcon";
global.__objectNames[86] = "ExtraLifeIcon";
global.__objectNames[87] = "FlameShieldIcon";
global.__objectNames[88] = "InvincibilityIcon";
global.__objectNames[89] = "MonitorIcon";
global.__objectNames[90] = "RingsIcon";
global.__objectNames[91] = "ShieldIcon";
global.__objectNames[92] = "SuperFormIcon";
global.__objectNames[93] = "SuperSpeedIcon";
global.__objectNames[94] = "ThunderShieldIcon";
global.__objectNames[95] = "Deactivable";
global.__objectNames[96] = "Solid";
global.__objectNames[97] = "CompetitionSignPost";
global.__objectNames[98] = "DefaultPlayerEntrance";
global.__objectNames[99] = "LampPost";
global.__objectNames[100] = "PlayerEntrance";
global.__objectNames[101] = "SignPost";
global.__objectNames[102] = "Sonic2LampPost";
global.__objectNames[103] = "Sonic2SignPost";
global.__objectNames[104] = "LostRing";
global.__objectNames[105] = "MagnetizedRing";
global.__objectNames[106] = "Ring";
global.__objectNames[107] = "WorldRing";
global.__objectNames[108] = "HeavyRectangle";
global.__objectNames[109] = "QuarterEllipse";
global.__objectNames[110] = "QuarterPipe";
global.__objectNames[111] = "Rectangle";
global.__objectNames[112] = "RightTriangle";
global.__objectNames[113] = "DiagonalSpring";
global.__objectNames[114] = "RedDiagonalSpring";
global.__objectNames[115] = "YellowDiagonalSpring";
global.__objectNames[116] = "RedSpring";
global.__objectNames[117] = "Spring";
global.__objectNames[118] = "YellowSpring";
global.__objectNames[119] = "SolidSwitch";
global.__objectNames[120] = "Switch";
global.__objectNames[121] = "BreakableWallDebris";
global.__objectNames[122] = "BreakableWall";
global.__objectNames[123] = "CrumblingFloor";
global.__objectNames[124] = "CrumblingFloorPiece";
global.__objectNames[125] = "QuarterEllipseConstruct";
global.__objectNames[126] = "QuarterPipeConstruct";
global.__objectNames[127] = "QuarterEllipseTerrain";
global.__objectNames[128] = "QuarterPipeTerrain";
global.__objectNames[129] = "RectangleTerrain";
global.__objectNames[130] = "RightTriangleTerrain";
global.__objectNames[131] = "Bubble";
global.__objectNames[132] = "BubbleCluster";
global.__objectNames[133] = "Water";
global.__objectNames[134] = "WaterBlend";
global.__objectNames[135] = "WaterRippleShader";
global.__objectNames[136] = "GameZone";
global.__objectNames[137] = "PauseControl";
global.__objectNames[138] = "ZoneCleanup";
global.__objectNames[139] = "ZoneTimeLimit";
global.__objectNames[140] = "ZoneRestart";
global.__objectNames[141] = "AzureLakeBackground";
global.__objectNames[142] = "TestRoomBackground";
global.__objectNames[143] = "ConveyorBelt";
global.__objectNames[144] = "Corkscrew";
global.__objectNames[145] = "MovableWater";
global.__objectNames[146] = "PushBlock";
global.__objectNames[147] = "SampleBreakableWall";
global.__objectNames[148] = "SampleBridge";
global.__objectNames[149] = "SampleScoreBumper";
global.__objectNames[150] = "BossEggMobile";
global.__objectNames[151] = "BossEggMobileEggman";
global.__objectNames[152] = "GHZBossChainBall";
global.__objectNames[153] = "GHZBossChainBase";
global.__objectNames[154] = "GHZBossChainLink";
global.__objectNames[155] = "GHZBossEggMobile";
global.__objectNames[156] = "DemoZoneBoss";
global.__objectNames[157] = "CrushBlock";
global.__objectNames[158] = "HorizontalMovingBlock";
global.__objectNames[159] = "VerticalMovingBlock";
global.__objectNames[160] = "CustomTerrain1";
global.__objectNames[161] = "CustomTerrain2";
global.__objectNames[162] = "CustomTerrain3";
global.__objectNames[163] = "FileSelectMenuChoice";
global.__objectNames[164] = "FileSelectMenuFileChoice";
global.__objectNames[165] = "FileSelectMenuCompleteFileChoice";
global.__objectNames[166] = "FileSelectMenuDeleteChoice";
global.__objectNames[167] = "FileSelectMenuExistingFileChoice";
global.__objectNames[168] = "FileSelectMenuNewFileChoice";
global.__objectNames[169] = "FileSelectMenuNoSaveChoice";
global.__objectNames[170] = "FileSelectMenu";
global.__objectNames[171] = "FileSelectMenuCursor";
global.__objectNames[172] = "FileSelectMenuDeleteIcon";
global.__objectNames[173] = "FileSelectMenuPage";
global.__objectNames[174] = "GameMenuChoice";
global.__objectNames[175] = "LabelledMenuChoice";
global.__objectNames[176] = "LabelledMouseSensitiveMenuChoice";
global.__objectNames[177] = "MouseSensitiveMenuChoice";
global.__objectNames[178] = "GameMenu";
global.__objectNames[179] = "GameMenuPage";
global.__objectNames[180] = "GameOverScreen";
global.__objectNames[181] = "TimeOverScreen";
global.__objectNames[182] = "ScoreTally";
global.__objectNames[183] = "Sonic2Display";
global.__objectNames[184] = "AnimatedGameSign";
global.__objectNames[185] = "AnimatedLabeledGameSign";
global.__objectNames[186] = "GameSign";
global.__objectNames[187] = "LabeledGameSign";
global.__objectNames[188] = "ZoneTitle";
global.__objectNames[189] = "ZoneTitleRedFold";
global.__objectNames[190] = "GameConsoleMessage";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for